[package]
name = "venndb-usage"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
venndb = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
