[package]
description = "an in-memory database in Rust for rows queried using bit (flag) columns"
edition = "2021"
homepage = "https://github.com/plabayo/flagdb"
license = "MIT"
name = "flagdb"
readme = "../README.md"
repository = "https://github.com/plabayo/flagdb"
version = "0.0.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
